version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "importer-lambda-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4g70yo9tcpt9"
s3_prefix = "importer-lambda-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
